import React from 'react'
import { Segment, Header, Divider } from 'semantic-ui-react'

const Welcome = () => (
  <Segment basic>
    <Header as='h1' textAlign='center'>
      <Header.Content>
        Castle Valley's Martial Arts and Physical Fitness Studio
      </Header.Content>
    </Header>
    <p>
      A proper Japanese martial arts dōjō is considered special and is well cared for by its users. Shoes are not worn in a dōjō. In many styles it is traditional to conduct a ritual cleaning (sōji) of the dōjō at the beginning and/or end of each training session. Besides the obvious hygienic benefits of regular cleaning it also serves to reinforce the fact that dōjō are supposed to be supported and managed by the student body (or by special students, e.g., uchi-deshi), not the school's instructional staff. This attitude has become lost in many modern dōjō that are founded and run by a small group of people or instructors.[citation needed] In fact, it is not uncommon that in traditional schools (koryu), dōjō are rarely used for training at all, instead being reserved for more symbolic or formal occasions. The actual training is conducted typically outdoors or in a less formal area.
      Many traditional dōjō follow a prescribed pattern with shomen ("front") and various entrances that are used based on student and instructor rank laid out precisely. Typically students will enter in the lower-left corner of the dōjō (in reference to the shomen) with instructors in the upper right corner. Shomen typically contains a Shintō shrine with a sculpture, flower arrangement, or other artifacts. The term kamiza means "place of honor" and a related term, kamidana refers to the shrine itself. Other artifacts may be displayed throughout the dōjō, such as kanban that authorize the school in a style or strategy, and items such as taiko drums or armor (yoroi). It is not uncommon to find the name of the dōjō and the dōjō kun (roughly "dōjō rules") displayed prominently at shomen as well. Visitors may have a special place reserved, depending on their rank and station. Weapons and other training gear will normally be found on the back wall.
    </p>
    <p>
      A proper Japanese martial arts dōjō is considered special and is well cared for by its users. Shoes are not worn in a dōjō. In many styles it is traditional to conduct a ritual cleaning (sōji) of the dōjō at the beginning and/or end of each training session. Besides the obvious hygienic benefits of regular cleaning it also serves to reinforce the fact that dōjō are supposed to be supported and managed by the student body (or by special students, e.g., uchi-deshi), not the school's instructional staff. This attitude has become lost in many modern dōjō that are founded and run by a small group of people or instructors.[citation needed] In fact, it is not uncommon that in traditional schools (koryu), dōjō are rarely used for training at all, instead being reserved for more symbolic or formal occasions. The actual training is conducted typically outdoors or in a less formal area.
      Many traditional dōjō follow a prescribed pattern with shomen ("front") and various entrances that are used based on student and instructor rank laid out precisely. Typically students will enter in the lower-left corner of the dōjō (in reference to the shomen) with instructors in the upper right corner. Shomen typically contains a Shintō shrine with a sculpture, flower arrangement, or other artifacts. The term kamiza means "place of honor" and a related term, kamidana refers to the shrine itself. Other artifacts may be displayed throughout the dōjō, such as kanban that authorize the school in a style or strategy, and items such as taiko drums or armor (yoroi). It is not uncommon to find the name of the dōjō and the dōjō kun (roughly "dōjō rules") displayed prominently at shomen as well. Visitors may have a special place reserved, depending on their rank and station. Weapons and other training gear will normally be found on the back wall.
    </p>
    <p>
      A proper Japanese martial arts dōjō is considered special and is well cared for by its users. Shoes are not worn in a dōjō. In many styles it is traditional to conduct a ritual cleaning (sōji) of the dōjō at the beginning and/or end of each training session. Besides the obvious hygienic benefits of regular cleaning it also serves to reinforce the fact that dōjō are supposed to be supported and managed by the student body (or by special students, e.g., uchi-deshi), not the school's instructional staff. This attitude has become lost in many modern dōjō that are founded and run by a small group of people or instructors.[citation needed] In fact, it is not uncommon that in traditional schools (koryu), dōjō are rarely used for training at all, instead being reserved for more symbolic or formal occasions. The actual training is conducted typically outdoors or in a less formal area.
      Many traditional dōjō follow a prescribed pattern with shomen ("front") and various entrances that are used based on student and instructor rank laid out precisely. Typically students will enter in the lower-left corner of the dōjō (in reference to the shomen) with instructors in the upper right corner. Shomen typically contains a Shintō shrine with a sculpture, flower arrangement, or other artifacts. The term kamiza means "place of honor" and a related term, kamidana refers to the shrine itself. Other artifacts may be displayed throughout the dōjō, such as kanban that authorize the school in a style or strategy, and items such as taiko drums or armor (yoroi). It is not uncommon to find the name of the dōjō and the dōjō kun (roughly "dōjō rules") displayed prominently at shomen as well. Visitors may have a special place reserved, depending on their rank and station. Weapons and other training gear will normally be found on the back wall.
    </p>
    <Divider />
  </Segment>
)

export default Welcome
